on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TEst
        run: |
          whoami
          id -u
          sudo whoami
          
